/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HandoffsIdRouteImport } from './routes/handoffs.$id'
import { Route as HandoffsNewRouteImport } from './routes/handoffs.new'
import { Route as IntegrationsAuraRouteImport } from './routes/integrations.aura'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsIdRoute = HandoffsIdRouteImport.update({
  id: '/handoffs/$id',
  path: '/handoffs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsNewRoute = HandoffsNewRouteImport.update({
  id: '/handoffs/new',
  path: '/handoffs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAuraRoute = IntegrationsAuraRouteImport.update({
  id: '/integrations/aura',
  path: '/integrations/aura',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/handoffs/new': typeof HandoffsNewRoute
  '/integrations/aura': typeof IntegrationsAuraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/handoffs/new': typeof HandoffsNewRoute
  '/integrations/aura': typeof IntegrationsAuraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/handoffs/new': typeof HandoffsNewRoute
  '/integrations/aura': typeof IntegrationsAuraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/settings' | '/handoffs/$id' | '/handoffs/new' | '/integrations/aura'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/settings' | '/handoffs/$id' | '/handoffs/new' | '/integrations/aura'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/handoffs/$id'
    | '/handoffs/new'
    | '/integrations/aura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  HandoffsIdRoute: typeof HandoffsIdRoute
  HandoffsNewRoute: typeof HandoffsNewRoute
  IntegrationsAuraRoute: typeof IntegrationsAuraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs/$id': {
      id: '/handoffs/$id'
      path: '/handoffs/$id'
      fullPath: '/handoffs/$id'
      preLoaderRoute: typeof HandoffsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs/new': {
      id: '/handoffs/new'
      path: '/handoffs/new'
      fullPath: '/handoffs/new'
      preLoaderRoute: typeof HandoffsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/aura': {
      id: '/integrations/aura'
      path: '/integrations/aura'
      fullPath: '/integrations/aura'
      preLoaderRoute: typeof IntegrationsAuraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  HandoffsIdRoute: HandoffsIdRoute,
  HandoffsNewRoute: HandoffsNewRoute,
  IntegrationsAuraRoute: IntegrationsAuraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
